apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cdbtest-app
  name: cdbtest-deployment
  namespace: oracle-database-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdbtest-app
  template:
    metadata:
      labels:
        app: cdbtest-app
    spec:
      containers:
      - env:
        - name: DBUSR
          value: system
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              key: sysadmin_pwd
              name: cdb1-secret
        - name: DBURL
          value: "(DESCRIPTION=(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=10.0.10.139)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=TESTPDB.subb6ffe018e.k8scluster1.oraclevcn.com)))"
        image: eu-frankfurt-1.ocir.io/frg6v9xlrkul/helidon-dbstat:latest
        imagePullPolicy: Always
        name: cmpdemoapp-container
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
      - name:  "ocr-reg-cred"
      restartPolicy: Always
